[package]
name = "dns-rr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
dashmap = "6.1.0"
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"
simple-dns = "0.10.1"
tokio = { version = "1", features = ["full"] }
